// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxmklewotbcfrvuboeaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4bWtsZXdvdGJjZnJ2dWJvZWF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTY1NjYsImV4cCI6MjA2NDAzMjU2Nn0.e2WZ__vEMSp7feFz76yzzI-up1vJtxulO2Aoc0DqQBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);